spring:
  application:
    name: activiti-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/activiti_db_test
    username: user_activiti_test
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
server:
  port: 8300
  
  

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
    