spring:
  application:
    name: admin-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/workflow_process_db
    username: user_wp
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
        
    
server:
  port: 8400


map-errors:
  sql-errors:
    process_form_name_UNIQUE: The name of the process form already exists.


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      