-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 12:40:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema workflow_process_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workflow_process_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workflow_process_db` DEFAULT CHARACTER SET utf8 ;
USE `workflow_process_db` ;

-- -----------------------------------------------------
-- Table `workflow_process_db`.`document_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_process_db`.`document_types` (
  `document_type_id` INT NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`document_type_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `document_type_id_UNIQUE` ON `workflow_process_db`.`document_types` (`document_type_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `code_UNIQUE` ON `workflow_process_db`.`document_types` (`code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `workflow_process_db`.`user_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_process_db`.`user_status` (
  `user_status_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`user_status_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_status_id_UNIQUE` ON `workflow_process_db`.`user_status` (`user_status_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `workflow_process_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_process_db`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `age` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fk_document_type_id` INT NOT NULL,
  `document_number` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `fk_user_status_id` INT NOT NULL COMMENT '\n',
  `address` VARCHAR(100) NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_document_type_id`
    FOREIGN KEY (`fk_document_type_id`)
    REFERENCES `workflow_process_db`.`document_types` (`document_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_status_id`
    FOREIGN KEY (`fk_user_status_id`)
    REFERENCES `workflow_process_db`.`user_status` (`user_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_id_UNIQUE` ON `workflow_process_db`.`users` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_document_type_id_idx` ON `workflow_process_db`.`users` (`fk_document_type_id` ASC) VISIBLE;

CREATE INDEX `users_document_number_idx` ON `workflow_process_db`.`users` (`document_number` ASC) VISIBLE;

CREATE INDEX `fk_user_status_id_idx` ON `workflow_process_db`.`users` (`fk_user_status_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `workflow_process_db`.`process_forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_process_db`.`process_forms` (
  `process_form_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `content_form` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`process_form_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `process_form_id_UNIQUE` ON `workflow_process_db`.`process_forms` (`process_form_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `process_form_name_UNIQUE` ON `workflow_process_db`.`process_forms` (`name` ASC) VISIBLE;

CREATE INDEX `process_form_name_idx` ON `workflow_process_db`.`process_forms` (`name` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
